// app/Components/PrivacyPolicyContent.tsx
import React from 'react';

const PrivacyPolicyContent = () => (
  <>
    <h4 className="text-lg font-semibold text-gray-700 mb-2">Privacy Policy</h4>
    <p className="mb-3">Last updated: {new Date().toLocaleDateString()}</p>

    <p className="mb-3">
      This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when
      You use the Service and tells You about Your privacy rights and how the law protects You.
    </p>
    <p className="mb-3">
      We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use
      of information in accordance with this Privacy Policy.
    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Interpretation and Definitions</h5>
    {/* ... (Similar to T&C, define terms like Personal Data, Usage Data, Cookies, Data Controller etc.) ... */}
    <p className="mb-3">
      <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
    </p>
    <p className="mb-3">
      <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
    </p>
    <p className="mb-3">
      <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your Browse history on that website among its many uses.
    </p>


    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Collecting and Using Your Personal Data</h5>
    <h6 className="text-sm font-semibold text-gray-700 mt-3 mb-1">Types of Data Collected</h6>
    <p className="mb-2">
      <strong>Personal Data:</strong> While using Our Service, We may ask You to provide Us with certain personally identifiable information
      that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
    </p>
    <ul className="list-disc list-inside mb-3 ml-4">
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Username</li>
      <li>Usage Data</li>
    </ul>

    <p className="mb-2">
      <strong>Usage Data:</strong> Usage Data is collected automatically when using the Service.
      Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type,
      browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those
      pages, unique device identifiers and other diagnostic data.
    </p>

    <h6 className="text-sm font-semibold text-gray-700 mt-3 mb-1">Information from Third-Party Social Media Services (Google Login)</h6>
     <p className="mb-3">
        The Company allows You to create an account and log in to use the Service through Google. If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Google account, such as Your name, Your email address, Your activities or Your contact list associated with that account. You may also have the option of sharing additional information with the Company through Your Google account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
    </p>


    <h6 className="text-sm font-semibold text-gray-700 mt-3 mb-1">Tracking Technologies and Cookies</h6>
    <p className="mb-3">
      We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.
      Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
      {/* ... (Detail types of cookies: Session, Persistent, etc.) ... */}
    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Use of Your Personal Data</h5>
    <p className="mb-2">AnonMsg may use Personal Data for the following purposes:</p>
    <ul className="list-disc list-inside mb-3 ml-4">
      <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
      <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
      <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
      <li>To contact You: To contact You by email regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
      {/* ... (Add other uses like providing news, managing requests, business transfers, etc.) ... */}
    </ul>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Sharing Your Personal Data</h5>
     <p className="mb-3">
        We do not sell Your Personal Data. We may share Your personal information in the following situations:
    </p>
    <ul className="list-disc list-inside mb-3 ml-4">
      <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You. (e.g., for hosting, analytics).</li>
      <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
      <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
       <li><strong>To comply with laws:</strong> We may disclose Your Personal Data in the good faith belief that such action is necessary to: Comply with a legal obligation; Protect and defend the rights or property of AnonMsg; Prevent or investigate possible wrongdoing in connection with the Service; Protect the personal safety of Users of the Service or the public; Protect against legal liability.</li>
    </ul>


    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Retention of Your Personal Data</h5>
    <p className="mb-3">
      AnonMsg will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
      We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we
      are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Security of Your Personal Data</h5>
    <p className="mb-3">
      The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet,
      or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your
      Personal Data, We cannot guarantee its absolute security.
    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Children&apos;s Privacy</h5>
    <p className="mb-3">
      Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information
      from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with
      Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13
      without verification of parental consent, We take steps to remove that information from Our servers.
    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Links to Other Websites</h5>
    <p className="mb-3">
      Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be
      directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
    </p>
    <p className="mb-3">
      We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites
      or services.

    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Changes to this Privacy Policy</h5>
    <p className="mb-3">
      We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on
      this page.
    </p>
    <p className="mb-3">
      We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update
      the &quot;Last updated&quot; date at the top of this Privacy Policy.
    </p>
    <p className="mb-3">
      You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective
      when they are posted on this page.
    </p>

    <h5 className="text-md font-semibold text-gray-700 mt-4 mb-2">Contact Us</h5>
    <p className="mb-3">
      If you have any questions about this Privacy Policy, You can contact us: info@anonmsg.fredmaina.com
    </p>
  </>
);

export default PrivacyPolicyContent;